# Generated by Django 3.2 on 2023-04-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_confirmationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator'), ('moderator', 'Moderator')], default='user', max_length=9, verbose_name='Роль'),
        ),
    ]
